name: CI/CD Run Tests
on:
  push:
    branches: [ master ]
    paths:
            - 'force-app/**'
  pull_request:
    branches: [ master ]
    paths:
            - 'force-app/**'         

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "Name of repository is ${{ github.repository }}."
      - run: echo "Name of branch is ${{ github.ref }}."
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event_name == 'push'
    - uses: actions/setup-node@v1
      with:
        node-version: '>=14'
        check-latest: true
   
    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
        echo y | tail -n +1 | sfdx plugins:install sfdx-git-delta
      
    - name: Populate auth file with SFDX_URL secret
      shell: bash
      run: 'echo ${{ secrets.ORG_AUTH_SECRET}} > SFDX_QA'

    - name: Authenticate Against Dev Hub
      run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_QA -s -a AramsLab
        
    - name: Run Apex Tests
      run: 
        node_modules/sfdx-cli/bin/run force:apex:test:run --resultformat tap --codecoverage -c -r human
        
    # - name: Deploy Source
    #   id: Deploy
    #   if: github.event_name == 'push'
    #   run:
    #     node_modules/sfdx-cli/bin/run force:source:deploy -p force-app -u AramsLab --json --loglevel fatal
